# Generated by Django 6.0.2 on 2026-03-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnbuResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evaluated_at', models.DateTimeField()),
                ('target_name', models.TextField()),
                ('metric_name', models.TextField(blank=True, null=True)),
                ('metric_value', models.BigIntegerField(blank=True, null=True)),
                ('severity', models.SmallIntegerField(blank=True, null=True)),
                ('state', models.TextField()),
                ('critical_val', models.BigIntegerField(blank=True, null=True)),
                ('major_val', models.BigIntegerField(blank=True, null=True)),
                ('minor_val', models.BigIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('action_name', models.TextField(blank=True, null=True)),
                ('datasource', models.TextField(blank=True, null=True)),
                ('scheduler_name', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('baseline', models.BigIntegerField(blank=True, null=True)),
                ('deviation', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anbu_result',
                'managed': False,
            },
        ),
    ]
